services:
  api:
    build:
      context: ./docker
      dockerfile: Dockerfile

    container_name: nodejs_learn_anything  

    working_dir: /app
    
    ports:
      - "${PORT}:${PORT}"
    
    # Mount your local source code into the container.
    volumes:
      - .:/app
    
    # First time node_modules folder init
    entrypoint: ["/bin/sh", "./docker/docker-entrypoint.sh"]

    # Override the default command for development.
    command: npm run dev
    
    # Define environment variables for API.
    environment:
      - NODE_ENV=development
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      